### ISSUE TITLE
Problem mit der Installation

### ISSUE THREAD

**Issue by stockklauser** [equitania/odoo-addons#6]
Hallo,

während der Installation Tritt die Meldung auf das ein Modul namens "polib" fehlt. 

Hier die Message:

Traceback (most recent call last):
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\http.py", line 530, in _handle_exception
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\http.py", line 567, in dispatch
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\http.py", line 303, in _call_function
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\service\model.py", line 113, in wrapper
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\http.py", line 300, in checked_call
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\http.py", line 796, in __call__
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\http.py", line 396, in response_wrap
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\openerp\addons\web\controllers\main.py", line 953, in call_button
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\openerp\addons\web\controllers\main.py", line 941, in _call_kw
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\api.py", line 241, in wrapper
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\openerp\addons\base\module\module.py", line 450, in button_immediate_install
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\api.py", line 241, in wrapper
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\openerp\addons\base\module\module.py", line 498, in _button_immediate_function
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\modules\registry.py", line 366, in new
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\modules\loading.py", line 355, in load_modules
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\modules\loading.py", line 255, in load_marked_modules
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\modules\loading.py", line 143, in load_module_graph
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\modules\module.py", line 315, in load_openerp_module
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\.\openerp\modules\module.py", line 80, in load_module
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\openerp\addons\equitania\__init__.py", line 22, in <module>
  File "D:\Programme\Odoo\Odoo 8.0-20150217\server\openerp\addons\equitania\eq_install_func.py", line 23, in <module>
ImportError: No module named polib

**Comment by eqms** [comment]
Lassen Sie das Prepare Skript für Ubuntu https://github.com/equitania/odoo-addons/blob/master/scripts/prepare-odoo-server-ubuntu.sh oder ggf. Debian https://github.com/equitania/odoo-addons/blob/master/scripts/prepare-odoo-server-debian.sh laufen.
Dort werden alle nötigen Libs installiert.

**Comment by stockklauser** [comment]
Hallo,

ich verwende einen Windows Server, somit funktionieren diese scripts nicht.

**Comment by eqms** [comment]
http://polib.readthedocs.org/en/latest/installation.html

**Comment by stockklauser** [comment]
Hallo,

ich habe gestern noch die POLIB Installiert.

![polib](https://cloud.githubusercontent.com/assets/7037938/6257131/f7e6da86-b7bd-11e4-8157-02ed40edba7a.JPG)
![error odoo](https://cloud.githubusercontent.com/assets/7037938/6257142/1a2a4448-b7be-11e4-8865-21c84d3a979a.JPG)

Leider bleibt das Problem wie auf dem Screenshot zu sehn erhalten.

**Comment by eqms** [comment]
Leider ist Python und Windows manchmal etwas inkompatibel.
Wir testen unsere Paket nur unter Linux und entwickeln auch dort.
Tut mir leid.

Wie wäre es denn mit einer VM mit Virtualbox und Linux.
Kostet nix und funktioniert schneller und zuverlässiger.
Mit meinen Skripten geht die Installation im Handumdrehen.

**Comment by ForCase** [comment]
Hallo Herr Stockklauser,
1. im Verzeichnis \Python-Dir\Lib\site-packages findest Du die beiden Dateien polib.py und polib.pyc.
2. Kopiere die beiden Dateien in das Verzeichnis *\odoo-Dir\server
3. kopiere das addon-Verzeichnis nach *\odoo-Dir\server\openerp\addons
4. Starte den odoo-Dienst neu
5. dann kannst Du wie üblich das Addon installieren

Viel Erfolg dabei.

**Comment by stockklauser** [comment]
Hallo 

Besten Dank an euch! Ich bin auf euer anraten auf Ubuntu 14 gegangen in einer Virtuellen Maschine... Dies ist auch Backup Technsich besser, da ich einen Dump von der Virtuellen machen kann.
